name: discussion telegram message
on: [discussion]
jobs:
  handle_discussion:
    name: HandleDiscussion
    runs-on: ubuntu-latest
    steps:
      - name: echo data
        run: |
          echo "action: ${{ github.action }}; sender: ${{ github.sender }}; discussion: ${{ github.discussion }}"
      - name: send telegram message when discussion created
        if: github.action == 'created'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.sender.login }} создал дискуссию: ${{ github.discussion.title }}
            url: ${{ github.discussion.html_url }}
      - name: send telegram message when discussion edited
        if: github.action == 'edited'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.sender.login }} обновил дискуссию: ${{ github.discussion.title }}
            url: ${{ github.discussion.html_url }}
      - name: send telegram message when discussion deleted
        if: github.action == 'deleted'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.sender.login }} удалил дискуссию: ${{ github.discussion.title }}
      - name: send telegram message when discussion pinned
        if: github.action == 'pinned'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.sender.login }} закрепил дискуссию: ${{ github.discussion.title }}
            url: ${{ github.discussion.html_url }}
      - name: send telegram message on discussion answered
        if: github.action == 'answered'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.sender.login }} закрыл дискуссию: ${{ github.discussion.title }}
            url: ${{ github.discussion.html_url }}
